import { HANTEO_MAMBER, Posts, TABS, Tech } from "@/types";

export const HANTEO_MEMBERS: HANTEO_MAMBER[] = [
  {
    id: 1,
    name: "박병서",
    role: "본부장",
    department: "서비스개발실",
    stack: [
      "백엔드 개발자",
      "프론트엔드 개발자",
      "서비스 매니저",
      "안드로이드 개발자",
    ],
    residence: "서울",
    dateOfEmployment: "Apr 1, 2024",
    info: "",
    linkedIn: "",
    email: "dev.bspark@hanteo.com",
    gmail: "dev.bspark@gmail.com",
    github: "",
    phone: "01068996794",
    likeFood: [],
  },
  {
    id: 2,
    name: "윤주성",
    role: "팀장",
    department: "서비스개발실",
    stack: ["풀스택"],
    residence: "서울",
    dateOfEmployment: "Feb 8, 2021",
    info: "",
    linkedIn: "",
    email: "pollalis2@hanteo.com",
    gmail: "pollalis2@gmail.com",
    github: "",
    phone: "01041378018",
    likeFood: [],
  },
  {
    id: 3,
    name: "김재운",
    role: "프로젝트 매니저",
    department: "서비스개발실",
    stack: ["풀스택", "IOS 개발자"],
    residence: "캐나다",
    dateOfEmployment: "Fabruary 1, 2019",
    info: "캠핑에 취미를 가져볼까합니다?",
    linkedIn: "http://www.linkedin.com/in/jaewoon-kim",
    email: "htjw@hanteo.com",
    gmail: "dnswkdl501@gmail.com",
    github: "https://github.com/JaeDev",
    phone: "01045319194",
    likeFood: [],
  },
  {
    id: 4,
    name: "이영훈",
    role: "주임",
    department: "서비스개발실",
    stack: ["안드로이드 개발자", "프론트엔드 개발자"],
    residence: "서울",
    dateOfEmployment: "Oct 20, 2020",
    info: "지금 거의 거렁뱅이예요",
    linkedIn: "",
    email: "twnthbb@hanteo.com",
    gmail: "twnthbb@gmail.com",
    github: "https://github.com/twnth",
    phone: "01083515080",
    likeFood: [
      "국밥",
      "라면",
      "짬뽕",
      "마라탕",
      "마라샹궈",
      "삼겹살",
      "오징어 덮밥",
      "아아",
      "곱창",
      "부대찌개",
    ],
  },
  {
    id: 5,
    name: "신동한",
    role: "주임",
    department: "서비스개발실",
    stack: ["백엔드 개발자"],
    residence: "서울",
    dateOfEmployment: "Feb 8, 2021",
    info: "",
    linkedIn: "",
    email: "donghans@hanteo.com",
    gmail: "b.donghans@gmail.com",
    github: "https://github.com/donghans",
    phone: "01064151647",
    likeFood: [],
  },
  {
    id: 6,
    name: "김준완",
    role: "사원",
    department: "서비스개발실",
    stack: ["??"],
    residence: "서울",
    dateOfEmployment: "Nov 8, 2023",
    info: "",
    linkedIn: "",
    email: "jwk7890@hanteo.com",
    gmail: "jjwwkk7890@gmail.com",
    github: "",
    phone: "01093977790",
    likeFood: [],
  },
  {
    id: 7,
    name: "류동재",
    role: "사원",
    stack: ["백엔드 개발자"],
    department: "서비스개발실",
    residence: "서울",
    dateOfEmployment: "Feb 7, 2022",
    info: "모든 건..기세다",
    linkedIn: "",
    email: "rdj1014@hanteo.com",
    gmail: "rdj10149@gmail.com",
    github: "https://github.com/ryudongjae",
    phone: "01079422492",
    likeFood: [],
  },
  {
    id: 8,
    name: "정지현",
    role: "사원",
    department: "서비스개발실",
    stack: ["백엔드 개발자"],
    residence: "서울",
    dateOfEmployment: "Oct 11, 2023",
    info: "",
    linkedIn: "",
    email: "ironprayer1208@hanteo.com",
    gmail: "ironprayer1209@gmail.com",
    github: "https://github.com/jeongjihuyn",
    phone: "01035370775",
    likeFood: [],
  },
  {
    id: 9,
    name: "이본훈",
    department: "서비스개발실",
    role: "사원",
    stack: ["프론트엔드 개발자"],
    residence: "서울",
    dateOfEmployment: "May 7, 2024",
    info: "",
    linkedIn: "",
    email: "opsizks4@hanteo.com",
    gmail: "opsizks4@gmail.com",
    github: "https://github.com/LeeBonHoon1",
    phone: "01021830828",
    likeFood: [],
  },
];

export const HANTEO_NEWS: Posts[] = [
  {
    id: 1,
    title: "방탄소년단, 새 앨범 'Butter' 발표",
    description:
      "'Butter'는 방탄소년단(BTS)의 새로운 앨범으로, 전세계적인 팬들에게 큰 관심을 받고 있습니다. 발매와 함께 음원 차트를 책임질 것으로 예상되는 이 앨범은 기대를 모으고 있습니다.",
  },
  {
    id: 2,
    title: "트와이스, 새 싱글 'Alcohol-Free' 공개",
    description:
      "한국의 걸 그룹 트와이스(TWICE)가 'Alcohol-Free'라는 새로운 싱글을 발표했습니다. 이 싱글은 여름 분위기를 담은 시원한 음악으로, 팬들의 호응을 얻고 있습니다.",
  },
  {
    id: 3,
    title: "아이유, 새 앨범 'LILAC'으로 음원 차트 석권",
    description:
      "아이유(IU)가 'LILAC'이라는 새 앨범을 발표하며 음원 차트를 석권했습니다. 그녀의 다채로운 음악 스타일과 감성적인 가사는 수많은 팬들의 마음을 사로잡고 있습니다.",
  },
  {
    id: 4,
    title: "빅뱅, 컴백 앨범 'Still Alive' 발표",
    description:
      "한국의 대표적인 보이 그룹 중 하나인 빅뱅(BIGBANG)이 'Still Alive'라는 컴백 앨범을 발표했습니다. 이전과는 다른 음악적 스타일로 돌아온 이들은 여전히 많은 관심을 받고 있습니다.",
  },
  {
    id: 5,
    title: "BLACKPINK, 미국 투어 일정 발표",
    description:
      "글로벌한 인기를 누리고 있는 걸 그룹 BLACKPINK가 미국 투어 일정을 발표했습니다. 팬들은 무대 위에서 그들의 화려한 퍼포먼스를 기대하고 있습니다.",
  },
  {
    id: 6,
    title: "아이즈원, 해체 후 각자의 활동 시작",
    description:
      "인기 걸 그룹 아이즈원(IZ*ONE)이 해체 후 각자의 솔로 활동을 시작했습니다. 그들의 새로운 도전에 많은 이들이 응원하고 있습니다.",
  },
  {
    id: 7,
    title: "오마이걸, 새 앨범 'Dun Dun Dance'로 컴백",
    description:
      "오마이걸(OH MY GIRL)이 'Dun Dun Dance'라는 새 앨범으로 컴백했습니다. 화려한 무대와 중독적인 멜로디로 팬들을 매료시킬 것으로 예상됩니다.",
  },
  {
    id: 8,
    title: "스트레이 키즈, 새 앨범 'NOEASY' 발표",
    description:
      "스트레이 키즈(Stray Kids)가 'NOEASY'라는 새 앨범을 발표했습니다. 이번 앨범은 그들의 성장과 변화를 보여주며, 다양한 음악적 스타일을 선보일 예정입니다.",
  },
  {
    id: 9,
    title: "레드벨벳, 유닛 활동으로 컴백 예정",
    description:
      "인기 걸 그룹 레드벨벳(RED VELVET)이 유닛 활동으로 컴백 예정입니다. 멤버들의 다채로운 음악 스타일과 화려한 무대가 기대됩니다.",
  },
  {
    id: 10,
    title: "모모랜드, 일본 프로젝트로 활동 재개",
    description:
      "걸 그룹 모모랜드(MOMOLAND)가 일본 프로젝트로 활동을 재개했습니다. 그들의 활약을 통해 일본 음악 시장에서도 큰 성과를 거둘 것으로 기대됩니다.",
  },
  {
    id: 11,
    title: "에드 시런, 새 앨범 'Equals' 발매 예정",
    description:
      "영국의 싱어송라이터 에드 시런(Ed Sheeran)이 새 앨범 'Equals'를 발매할 예정입니다. 많은 팬들이 그의 새로운 음악에 대한 기대감을 가지고 있습니다.",
  },
  {
    id: 12,
    title: "비틀즈, 전설적 앨범 'Abbey Road' 발매 50주년 기념",
    description:
      "전설적인 밴드 비틀즈(The Beatles)의 앨범 'Abbey Road'가 발매된 지 50주년을 기념하여 특별한 이벤트가 진행될 예정입니다. 팬들은 이 비틀즈의 레전드를 다시 한번 경험할 수 있을 것입니다.",
  },
  {
    id: 13,
    title: "레이디 가가, 월드투어 'Chromatica Ball' 개최 예정",
    description:
      "팝 아티스트 레이디 가가(Lady Gaga)가 월드투어 'Chromatica Ball'을 개최할 예정입니다. 이 투어는 그녀의 최신 앨범 'Chromatica'를 홍보하고 팬들과의 만남을 갖기 위한 것입니다.",
  },
  {
    id: 14,
    title: "빌리 아일리시, 새 싱글 'NDA' 공개",
    description:
      "빌리 아일리시(Billie Eilish)가 'NDA'라는 새로운 싱글을 공개했습니다. 그의 독특한 음악 스타일과 가사는 많은 이들의 사랑을 받고 있습니다.",
  },
  {
    id: 15,
    title: "마크 러플로, 새 앨범 'Love Goes' 발매",
    description:
      "영국의 싱어송라이터 마크 러플로(Mark Ronson)가 'Love Goes'라는 새 앨범을 발매했습니다. 이 앨범은 그의 감성적인 음악과 가사로 많은 이들의 마음을 사로잡고 있습니다.",
  },
  {
    id: 16,
    title: "브루노 마스, 새 싱글 'Leave the Door Open' 인기",
    description:
      "브루노 마스(Bruno Mars)의 새로운 싱글 'Leave the Door Open'이 큰 인기를 끌고 있습니다. 그의 부드러운 보컬과 리듬은 많은 이들의 귀를 사로잡고 있습니다.",
  },
  {
    id: 17,
    title: "리한나, 코스메틱 브랜드 'Fenty Beauty' 새 제품 발매",
    description:
      "리한나(Rihanna)가 운영하는 코스메틱 브랜드 'Fenty Beauty'가 새로운 제품을 발매했습니다. 이번 제품은 많은 이들의 관심을 받으며 높은 판매량을 기록할 것으로 예상됩니다.",
  },
  {
    id: 18,
    title: "존 레전드, 새 앨범 'Bigger Love' 석권",
    description:
      "R&B 가수 존 레전드(John Legend)가 'Bigger Love'라는 새 앨범을 석권했습니다. 그의 감미로운 음색과 멋진 앨범은 많은 이들에게 사랑을 받고 있습니다.",
  },
  {
    id: 19,
    title: "디지털 리모스, 새 앨범 'Future Nostalgia'로 음원 차트 1위",
    description:
      "영국의 싱어송라이터 디지털 리모스(Dua Lipa)가 'Future Nostalgia'라는 새 앨범으로 음원 차트 1위를 차지했습니다. 그의 중독성 있는 음악은 많은 이들의 사랑을 받고 있습니다.",
  },
  {
    id: 20,
    title: "아리아나 그란데, 새 싱글 'Positions' 인기",
    description:
      "팝 가수 아리아나 그란데(Ariana Grande)의 새 싱글 'Positions'이 큰 인기를 끌고 있습니다. 그의 강렬한 보컬과 중독성 있는 멜로디는 많은 이들의 귀를 사로잡고 있습니다.",
  },
  {
    id: 21,
    title: "테일러 스위프트, 새 앨범 'Red (Taylor's Version)' 발매 예정",
    description:
      "포플 아티스트 테일러 스위프트(Taylor Swift)가 'Red (Taylor's Version)'라는 앨범을 발매할 예정입니다. 팬들은 그녀의 과거 히트곡들을 새롭게 재해석한 이번 앨범에 많은 기대를 가지고 있습니다.",
  },
  {
    id: 22,
    title: "비야, 새 싱글 'BAILA BAILA BAILA' 인기",
    description:
      "라틴 가수 비야(Becky G)의 새 싱글 'BAILA BAILA BAILA'가 큰 인기를 얻고 있습니다. 그의 열정적인 보컬과 중독성 있는 리듬은 많은 이들을 사로잡고 있습니다.",
  },
  {
    id: 23,
    title: "마이클 잭슨, 'Thriller' 앨범 40주년 기념",
    description:
      "전설적인 팝 아티스트 마이클 잭슨(Michael Jackson)의 앨범 'Thriller'이 발매된 지 40주년을 기념하는 이벤트가 진행될 예정입니다. 그의 레전더리한 음악은 여전히 많은 이들의 사랑을 받고 있습니다.",
  },
  {
    id: 24,
    title: "케이티 페리, 새 싱글 'Electric' 공개",
    description:
      "팝 가수 케이티 페리(Katy Perry)가 'Electric'이라는 새로운 싱글을 공개했습니다. 그의 특유의 화려한 무대와 캐치한 멜로디는 많은 이들의 관심을 끌고 있습니다.",
  },
  {
    id: 25,
    title: "제시, 새 앨범 'BE' 발매",
    description:
      "랩퍼 제시(Jessi)가 'BE'라는 새 앨범을 발매했습니다. 그의 강렬한 퍼포먼스와 다채로운 음악은 많은 이들의 마음을 사로잡고 있습니다.",
  },
  {
    id: 26,
    title: "샘 스미스, 새 앨범 'Love Goes' 발표",
    description:
      "영국의 싱어송라이터 샘 스미스(Sam Smith)가 'Love Goes'라는 새 앨범을 발표했습니다. 그의 감성적인 음악은 수많은 이들에게 위로와 감동을 전해주고 있습니다.",
  },
  {
    id: 27,
    title: "트래비스 스콧, 새 앨범 'Utopia' 예고",
    description:
      "래퍼 트래비스 스콧(Travis Scott)이 새 앨범 'Utopia'를 예고했습니다. 그의 파격적인 음악과 무대는 항상 많은 이들의 이목을 끌고 있습니다.",
  },
  {
    id: 28,
    title: "마돈나, 'True Blue' 앨범 35주년 기념 리이슈",
    description:
      "팝 아이콘 마돈나(Madonna)의 앨범 'True Blue'가 발매된 지 35주년을 맞아 리이슈되었습니다. 그의 히트곡들은 여전히 많은 이들의 마음을 사로잡고 있습니다.",
  },
  {
    id: 29,
    title: "블랙 아이드 피스, 새 싱글 'GIRL LIKE ME' 히트",
    description:
      "글로벌 그룹 블랙 아이드 피스(Black Eyed Peas)의 새 싱글 'GIRL LIKE ME'가 큰 인기를 끌고 있습니다. 그들의 다채로운 음악은 많은 이들의 마음을 사로잡고 있습니다.",
  },
  {
    id: 30,
    title: "테일러 스위프트, 'Fearless (Taylor's Version)' 앨범 발매",
    description:
      "포플 아티스트 테일러 스위프트(Taylor Swift)가 'Fearless (Taylor's Version)'이라는 앨범을 재발매했습니다. 그녀의 과거 히트곡들을 새롭게 재해석한 이번 앨범은 많은 이들의 사랑을 받고 있습니다.",
  },
];

export const tabs: TABS[] = [
  {
    id: 1,
    name: "Hanteo board",
    active: false,
    href: "/",
  },
  {
    id: 2,
    name: "Tech research",
    active: false,
    href: "/tech",
  },
];

export const description =
  '<p><span style="color:#000000;"><img src="https://lh7-us.googleusercontent.com/JFRD0OMhD7-Fjw1SUd3W0PzBTVKNo0NiXcL89AfG0_o8ffbJYHQtXfaU6XGwLMQdi49ol7SdEdFbueGvaluSU9egjNgGt87_qNQOzka7TM4-52kEQq1Exwg-bS-tzeBOSP2vHqhNIfLdvfIL2ElYA-U">(사진=하이업엔터테인먼트 제공)</span></p><p>&nbsp;</p><p><span style="color:#000000;">그룹 스테이씨(STAYC)가 ‘페스티벌을 빛낼 아이돌’ 1위에 올랐어요👏 지난 5월 7일부터 13일까지 ‘[WhosPICK] 페스티벌을 빛낼 아이돌’이라는 주제로 투표를 진행한 후즈팬(Whosfan)!</span></p><p>&nbsp;</p><p><span style="color:#000000;">이번 투표에서는 스테이씨가 46.34%의 득표율로 1위를 차지했어요. 이어 세븐틴(21.19%)과 아이브(15.45%)가 차례로 2위와 3위에 이름을 올렸답니다.</span></p><p>&nbsp;</p><p><span style="color:#000000;">오늘 ‘후즈픽:뷰’에서는 ‘페스티벌을 빛낼 아이돌‘ 1위인 스테이씨에 대해 소개해볼게요!</span></p><p><br>&nbsp;</p><p><span style="font-size:18px;">🎈무대를 뜨겁게 달구는 실력</span></p><p>&nbsp;</p><p>이미 스테이씨의 실력은 케이팝 팬들이라면 모두 알고 있을 텐데요, 이런 실력 덕분인지 스테이씨가 가는 곳은 역대급 페스티벌이 된다는 사실✨<br>&nbsp;</p><figure class="media"><div data-oembed-url="https://youtu.be/qiIu7lFvMtg?si=xzpPLneZ1c1JgMIu"><div class="youtube-wrapper"><iframe class="youtube-video" width="100%" src="https://www.youtube.com/embed/qiIu7lFvMtg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div></div></figure><p>&nbsp;</p><p>스테이씨의 실력을 제대로 보여주는 영상인 ‘한국방송대상’의 축하 공연 영상! 짱테이씨답게 격한 안무를 하면서도 안정적인 라이브를 보여줬답니다!</p><p>&nbsp;</p><figure class="media"><div data-oembed-url="https://youtu.be/nkEaq5UUHuY?si=7UAthLb_2RvEZHyp"><div class="youtube-wrapper"><iframe class="youtube-video" width="100%" src="https://www.youtube.com/embed/nkEaq5UUHuY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div></div></figure><p>&nbsp;</p><p>그리고 남자 아이돌 그룹 곡 커버도 완벽하게 해낸 짱테이씨! 수트착장으로 보여주는 ‘Love Shot’이라니.. 스윗 어깨 올라가는 소리가 여기까지 들리네요😆</p><p>&nbsp;</p><figure class="media"><div data-oembed-url="https://youtu.be/b_oLOrVBJaw?si=N5AbhnWfnXU9-V-Z"><div class="youtube-wrapper"><iframe class="youtube-video" width="100%" src="https://www.youtube.com/embed/b_oLOrVBJaw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div></div></figure><p>&nbsp;</p><p>그리고 스테이씨의 노력과 실력을 한 번에 볼 수 있는 레코딩 비하인드까지 시청한다면, 평생 스윗 당첨💖</p><p>&nbsp;</p><p>&nbsp;</p><p><span style="font-size:18px;"><strong>🎈 공연에 맞춘 찰떡 스타일링</strong></span></p><p>&nbsp;</p><p>스테이씨는 센스 있는 스타일링으로도 유명한데요, 특히 대학교 축제에서는 대학교 대표 색상 또는 굿즈 등을 활용한 코디를 보여주기도 했습니다!<br>&nbsp;</p><p><span style="color:#000000;"><img src="https://lh7-us.googleusercontent.com/3PakwRIkog_bZylIf9wT4F0sVYrP2myGgapojq7qon_VUC1ZSuJdC_VQAcI00wtooDhQ96pIY089rlA0CPXqXd800_Yz0dqPJ1cSYxLZIV7F9XAXPPjIJusLFvdbq3j6gvO3QUhwXbCOrFo3RDAtjGQ">(사진=스테이씨 공식 X)</span></p><p>&nbsp;</p><p><span style="color:#000000;">경희대학교 축제에서 교색인 ‘경희레드’와 굿즈를 활용한 센스만점 스타일링을 보여준 스테이씨! 통일감있는 스타일링과 스테이씨 미모 덕에 오늘도 스윗 눈은 편안..😍</span></p><p>&nbsp;</p><p><span style="color:#000000;"><img src="https://lh7-us.googleusercontent.com/t93OSxTe-IxULCVwqJ45qDyjbzc4JR68cRzhXey4lKnUrKFoujb_lg8yWnFdy8eWcBL0cyL-oTj_ZMqF_TGkehlL51H-qAzMJ8b8XS0VNGecdANJHkYy0OzNUW2sLuc8oO-akgMAYP7LeHKfYKJgBT4"></span></p><p><span style="color:#000000;"><img src="https://lh7-us.googleusercontent.com/DCutpTrgIz3LMpyT7OwvDT5FXEWkaPXaAHtm10vfM29ihYen6q77CUucv6Pw8MQmzMXmcYGTTOZ1wYLh2p3wKP3NBXewnDYG2Rd-_XRSS_LlNBeQ8RCdvgSyBcsAs-BN6DTKLZ0Vj4ajBY_Fer8ea6M"></span></p><p><span style="color:#000000;">(사진=스테이씨 공식 인스타그램)</span></p><p>&nbsp;</p><p>그리고 행사 종료 후 경희대학교의 캐릭터인 ‘쿠옹’과 찍은 셀카를 올려준 시은과 경희대학교 유니폼 착장으로 셀카도 올려준 센스만점 시은과 윤!</p><p>&nbsp;</p><p><span style="color:#000000;"><img src="https://lh7-us.googleusercontent.com/B2rK22IhoI8SfCTVPQqNRTIFDOZSg9LR0M2-XsocuyFpgW6g28ljY5onFgbX7UYmrnYeVd9ZTNN8GTYcI8DtvRmCv-gxfBf21HmaqF_E4ClP7Sn2fBxPl1X5r4QZ7v9lbTPHNV6jPBp9oow9-tr7Mrg">(사진=스테이씨 공식 X)</span></p><p>&nbsp;</p><p><span style="color:#000000;">스테이씨하면 ‘숙명여자대학교’도 빠질 수 없겠죠?! 스스테이씨를 부르는 애칭 중 하나인 ‘숙대입시’를 활용한 슬로건까지 더해져 사랑스러운 축제였는데요, 이에 스테이씨는 숙명여자대학교의 캐릭터인 ‘눈송이’를 활용한 귀여운 스타일링을 보여줬어요💙</span></p><p>&nbsp;</p><p><span style="font-size:18px;"><strong>🎈 떼창도 가능🙆‍♂️ 히트곡 다수 보유 그룹 짱테이씨🧡&nbsp;</strong></span></p><p>&nbsp;</p><figure class="media"><div data-oembed-url="https://youtu.be/gMe1c4UegBY?si=PoOe_OQHvZTIf9Qu"><div class="youtube-wrapper"><iframe class="youtube-video" width="100%" src="https://www.youtube.com/embed/gMe1c4UegBY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div></div></figure><p>&nbsp;</p><p><span style="color:#000000;">스테이씨 하면 절대 빼놓을 수 없는 곡이죠! 바로 스테이씨의 ✨시작✨을 알린 곡,&nbsp; \'SO BAD\'입니다! 데뷔 때부터 완벽한 비주얼과 실력 그리고 신인답지 않은 프로페셔널함까지 완성형 아이돌임을 보여줬답니다 (●ˇ∀ˇ●)</span><br>&nbsp;</p><p>&nbsp;</p><figure class="media"><div data-oembed-url="https://youtu.be/SxHmoifp0oQ?si=R9qG5LW7_U1Iq0Zh"><div class="youtube-wrapper"><iframe class="youtube-video" width="100%" src="https://www.youtube.com/embed/SxHmoifp0oQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div></div></figure><p>&nbsp;</p><p>그리고 \'Teddy Bear\'도 절대 빠질 수 없는 곡인데요! 많은 케이팝 팬들이 최애가 해주길 바랐던 챌린지일 정도로 💛사랑스러운 안무💛와 🐻중독성 있는 후렴구🐻가 매력적인 곡!</p><p>모든 곡이 명곡이자 히트곡인 스테이씨인 만큼 세곡만 추천드리고 정말 아쉬운데요😥 아래 밴드 사운드와 함께한 스테이씨의 히트곡 모음도 함께 보는 것을 추천드려요!<br>&nbsp;</p><figure class="media"><div data-oembed-url="https://youtu.be/nyq_S7N7Ygo?si=fqujxKAgELepFkr6"><div class="youtube-wrapper"><iframe class="youtube-video" width="100%" src="https://www.youtube.com/embed/nyq_S7N7Ygo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div></div></figure><p>&nbsp;</p><p><span style="font-size:18px;">🎁1위 보상 및 이번 주 투표 안내🗳️</span></p><p>&nbsp;</p><p>후즈팬은 이번 투표에서 1위를 차지한 연준을 위해 일주일간 앱 내에서 팝업 광고를 진행할 예정입니다! 광고가 진행되는 ‘후즈팬 앱(Whosfan App)’은 모바일 앱스토어 및 플레이 스토어, 갤럭시 스토어에서 다운로드 가능해요.</p><p>&nbsp;</p><p>이번 주 \'후즈픽\'의 주제는 ’졸업 사진도 화보로 만들 것 같은 아이돌은?\'입니다! 졸업 사진도 화보로 만들 완성형 비주얼의 아이돌들이 후보로 자리해 있으니 많은 투표 부탁드려요. 이번 투표는 5월 14일부터 5월 20일까지 진행되니 놓치지 마세요!</p>';

export const TECHS: Tech[] = [
  {
    _id: "662f7d6809ef26f5a0b89f72",
    title: "온보딩 키트 리뉴얼 스토리 Ready to Break it?",
    subtitle: "온보딩 키트 브랜딩 및 굿즈 제작기",
    authorId: "W",
    date: "2024.04.30",
    slug: "onboardingkit-branding",
    category: "e",
    tag: [],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/87/87fc0164-8b88-4958-b5b5-037e56761564.png",
    id: "24ab",
  },
  {
    _id: "6618ea96fcab1c91395225d9",
    title: "생성 AI를 통해 모델 이미지 문제 해결하기",
    subtitle: "AI를 활용한 이미지 생성부터 문제 해결까지",
    authorId: "k.kang@healingpaper.com",
    date: "2024.04.12",
    slug: "GenerativeAI",
    category: "e",
    tag: ["b", "H", "generative", "ai"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/d0/d0370ab8-3194-4cd6-9ca8-15c49739c00e.jpeg",
    id: "c33b",
  },
  {
    _id: "65f7f9697412175715240602",
    title: "[SaaS] 시간여행이 가능한 시스템 아키텍처",
    subtitle: "복잡한 의료 도메인에 Event Sourcing 적용",
    authorId: "j",
    date: "2024.03.18",
    slug: "saas-event-sourcing",
    category: "i",
    tag: ["EventSourcing", "Event-Driven", "DDD", "D", "w"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/32/323f4b64-2972-482c-86c3-4720c1da239c.png",
    id: "38d3",
  },
  {
    _id: "65b3698ac840300a72651fcd",
    title: "클릭 한 번으로 Figma에 Notion 페이지 연동하기",
    subtitle: "피그마 위젯을 직접 개발해 제품 정책 파편화를 해결했어요.",
    authorId: "evan.lee@healingpaper.com",
    date: "2024.01.26",
    slug: "figma-widget-connecting-notion",
    category: "m",
    tag: ["figma", "notion", "documentation", "widget"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/7a/7a6e7284-11f9-4d55-a247-a0d662219636.png",
    id: "cd3c",
  },
  {
    _id: "65acd3fb84816ef17cf29b71",
    title: "[SaaS] 고객도 모르는 고객의 모든 것을 알아내기",
    subtitle:
      "실패시리지 - 고객을 충분히 알고 있다는 착각, 이로 인한 실패, 이를 통한 배움",
    authorId: "o",
    date: "2024.01.22",
    slug: "find-what-customers-really-want",
    category: "v",
    tag: ["5whys", "인터뷰", "C", "시뮬레이션", "고객집착"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/bd/bd812614-23fd-4564-bb74-c08cccf08cd8.webp",
    id: "9fb3",
  },
  {
    _id: "656800b908a6c7a8f1c24b4b",
    title: "글로벌 고객은 어떻게 사용할까?",
    subtitle: " 도쿄 출장기",
    authorId: "p",
    date: "2023.11.30",
    slug: "GlobalUserTest",
    category: "e",
    tag: ["M", "q", "일본"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/02/02fd8a4b-06f7-4ab1-9fe1-11ea212735bf.jpeg",
    id: "f3c5",
  },
  {
    _id: "6544bd752655b3c58cb9edab",
    title: "[SaaS] 프론트엔드 개발자가 API를 설계하는 이유",
    subtitle: "IDL을 이용한 효율적인 인터페이스 관리 전략",
    authorId: "eddy.an@healingpaper.com",
    date: "2023.11.03",
    slug: "saas-why-do-frontend-developers-design-api",
    category: "i",
    tag: ["IDL", "Google Protocol Buffer", "인터페이스 관리"],
    status: "t",
    thumbnailUrl: null,
    id: "941d",
  },
  {
    _id: "6501971ec16ef7854e34e792",
    title: "비즈니스 파트너와 함께 성장하는 방법",
    subtitle: "병원과 함께 성장하는 전략. 사업팀과 영업팀이 함께 찾아내다!",
    authorId: "sienna.sim+eva.son@healingpaper.com",
    date: "2023.09.14",
    slug: "growup-with-partner",
    category: "G",
    tag: ["플랫폼 비즈니스", "영업전략", "파트너성장", "성장 플레이북"],
    status: "t",
    thumbnailUrl: null,
    id: "22ee",
  },
  {
    _id: "64d9e16a2033e0747161c7af",
    title:
      "[SaaS] Enterprise 환경으로 확장하기 쉬운 Multi-Tenancy 서비스 구축하기",
    subtitle: "Kubernetes 기반의 Manifest, DB, Multi Version 관리",
    authorId: "j",
    date: null,
    slug: "saas-enterprise-multi-tenancy",
    category: "i",
    tag: ["mongodb", "AWS EKS", "docker", "gomplate", "쿠버네티스"],
    status: "t",
    thumbnailUrl: null,
    id: "d3bb",
  },
  {
    _id: "64d4a4973a80c370b4c63176",
    title: "[SaaS] Private AWS EKS Cluster With Github Actions",
    subtitle:
      "깃헙 액션으로 Private 쿠버네티스 클러스터 CI/CD 파이프라인 구축기",
    authorId: "j",
    date: null,
    slug: "saas-private-aws-eks",
    category: "i",
    tag: ["Git", "Github Action", "EKS", "Self-hosted Runner"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/a2/a27d19a0-0268-425a-bf72-b76216a259ae.png",
    id: "4850",
  },
  {
    _id: "64cccd7300ea887ad514f857",
    title: "[SaaS] Micro Frontends를 위해 Module Federation 적용하기",
    subtitle:
      "복잡하고 거대한 제품을 효과적으로 개발, 운영, 배포하기 위한 고민과 도전",
    authorId: "carter.gil@healingpaper.com",
    date: null,
    slug: "saas-microfrontends",
    category: "m",
    tag: ["micro-frontends", "module-federation", "webpack", "react"],
    status: "t",
    thumbnailUrl: null,
    id: "a77e",
  },
  {
    _id: "64d4a3a83d89092de27d3741",
    title: "[SaaS] 병원향 B2B SaaS 제품에 도전합니다",
    subtitle: "시장을 변화시키기 위한 남다른 제품과 기술의 시작",
    authorId: "o",
    date: "2023.08.13",
    slug: "saas-prologue",
    category: "v",
    tag: ["C", "SaaS", "Solutions", "CRM", "Multi-Tenancy"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/7b/7b86e906-7887-4cea-a442-c5d3ff7c1c62.jpeg",
    id: "87da",
  },
  {
    _id: "64d04796eab8b0e95291e07a",
    title: "B2B 프로덕트에서 고객의 흔적 찾기",
    subtitle: "직감에 의존하지 않고 고객 중심으로 설계하는 경험",
    authorId: "B",
    date: "2023.08.07",
    slug: "design-in-b2bproducts",
    category: "e",
    tag: ["b", "C", "J", "UX", "ProductDesigner"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/d0/d0c7a0c3-4903-4f46-a146-c14de1fd0216.png",
    id: "c43b",
  },
  {
    _id: "64a6304371373c252fccc475",
    title: "분산 시스템에서 메시지 안전하게 다루기",
    subtitle: "Transactional Outbox Pattern을 이용한 결과적 일관성 확보",
    authorId: "O",
    date: "2023.07.06",
    slug: "transactional-outbox",
    category: "i",
    tag: ["Transactional Outbox", "Message"],
    status: "t",
    thumbnailUrl: null,
    id: "c398",
  },
  {
    _id: "64913d34fbf9d4967069c63e",
    title: "실험하려다 파편화 부채를 청산했어요.",
    subtitle: "상담, 예약, 결제 완료 화면 개선기",
    authorId: "heydee.kim@healingpaper.com",
    date: "2023.06.20",
    slug: "design-consistency",
    category: "e",
    tag: ["b", "product", "ux", "ui"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/de/de3c2b97-3836-4eb1-92fd-f121c690c743.png",
    id: "ef54",
  },
  {
    _id: "64636a417831fd0ec5b08084",
    title: "변별력을 200% 더 높인 개발자 채용 방법: 코드 리뷰 테스트",
    subtitle: "요즘 개발자 채용 방법",
    authorId: "woogie.jeon@healingpaper.com",
    date: "2023.05.17",
    slug: "code-review-test",
    category: "i",
    tag: ["개발자 채용", "코딩 테스트", "코드 리뷰 테스트"],
    status: "t",
    thumbnailUrl: null,
    id: "d1bb",
  },
  {
    _id: "64426ffed616c837cc99068e",
    title: "비즈니스 자가진단 키트가 있다",
    subtitle: "사업의 건전성을 확인하는 방법",
    authorId: "mondri.an+kate.min@healingpaper.com",
    date: "2023.04.26",
    slug: "business-metric",
    category: "G",
    tag: ["비즈니스", "데이터", "사업관리"],
    status: "t",
    thumbnailUrl: null,
    id: "db1c",
  },
  {
    _id: "642eafe2b673b7c2cbdaba08",
    title: "극도의 솔직함을 위한 CSS 피드백 #1",
    subtitle: "동료들이 기다리는 피드백 시간이 있다?!",
    authorId: "o",
    date: "2023.04.06",
    slug: "css-1",
    category: "l",
    tag: [
      "피드백",
      "CSS",
      "Feedback",
      "솔직함",
      "심리적안정감",
      "피어리뷰",
      "동료",
    ],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/82/828330c2-cf61-4203-aeb4-65223bbf12c9.png",
    id: "61d4",
  },
  {
    _id: "63fd822e83d7623a63b612f9",
    title: "팀의 핵심가치 브랜딩하기",
    subtitle: "Core Value Evangelist 브랜딩 및 굿즈 제작 스토리",
    authorId: "W",
    date: "2023.03.06",
    slug: "cve_branding",
    category: "e",
    tag: [],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/5d/5dab140e-480b-47a1-934c-8a389041a3cf.png",
    id: "6b95",
  },
  {
    _id: "63e0bea44dfc5cfbe3387a82",
    title: "트랜잭션은 도메인 모델이 아니다",
    subtitle: "IoC를 이용한 데이터 원자성 확보",
    authorId: "O",
    date: "2023.02.06",
    slug: "isolate-transaction-from-domain-model",
    category: "i",
    tag: ["Inversion of Control", "Domain Driven Design", "z"],
    status: "t",
    thumbnailUrl: null,
    id: "c943",
  },
  {
    _id: "63aadcf7df5d9608c73d3f8f",
    title: "PO가 비즈니스 전략을 제품에 녹이는 방법 ",
    subtitle: "고객의 문제와 비즈니스 성장 사이에서 교집합 찾기",
    authorId: "F",
    date: "2023.01.05",
    slug: "how-to-reflect-business-strategy-in-your-product",
    category: "v",
    tag: ["지역확장", "PO", "제품개선", "전략", "N", "검색", "홈"],
    status: "t",
    thumbnailUrl: null,
    id: "b7e5",
  },
  {
    _id: "62a2f180b92ceed37c7967eb",
    title: "목적을 생각하면, 일하는 방식이 바뀐다",
    subtitle: "현재 무엇을 가장 중요하게 생각하나요?",
    authorId: "woody.kim@healingpaper.com",
    date: "2022.06.13",
    slug: "whywework",
    category: "r",
    tag: ["Q", "d"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/4c/4c5f1c37-92e4-4289-9c29-f5b11b2db546.png",
    id: "4bd9",
  },
  {
    _id: "624cfc03ec1048499aae888c",
    title: "3년째 OKR로 일하는 방법",
    subtitle: "OKR 도입 전과 후, 완전히 다른 회사가 되었습니다.",
    authorId: "s",
    date: "2022.04.06",
    slug: "okr",
    category: "l",
    tag: ["OKR", "Objective", "목표달성", "Q", "d"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/b1/b190c078-744a-4d2a-800c-a2488b4d4d16.png",
    id: "768a",
  },
  {
    _id: "622ecc35e1ff9161b1a80f12",
    title: "고객의 문제를 찾는 방법",
    subtitle: "정성적, 정량적 다양한 방법들을 알아보자",
    authorId: "p",
    date: "2022.03.16",
    slug: "userproblem",
    category: "e",
    tag: ["고객의문제", "정성적", "정량적", "VOC", "q", "데이터"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/ec/ec35aecc-a645-4f43-ace0-ecae5efcdabc.png",
    id: "01c5",
  },
  {
    _id: "622a0943ec1048229aae86b6",
    title: "고객의 문제를 작고 빠르게 해결하기 위해 필요한 3가지 ",
    subtitle:
      "고객의 문제를 어떻게 정의하고, 어떤 단계로 제품을 만들어 가치를 전달하는지 소개합니다.",
    authorId: "F",
    date: "2022.03.11",
    slug: "how-to-build-a-product",
    category: "r",
    tag: [],
    status: "t",
    thumbnailUrl: null,
    id: "7fc2",
  },
  {
    _id: "62232fe1ec10489438ae865e",
    title: "우리는 고객을 전혀 모르고 있었어요.. UT를 하기 전까지는요..!",
    subtitle: "사용성 테스트(UT)를 빠르게 팀에 도입하는 방법",
    authorId: "y",
    date: "2022.03.07",
    slug: "usability-test-team",
    category: "e",
    tag: ["ut", "usabilitytest", "M", "X"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/6e/6e652db5-0f1c-4592-92d8-cc6043f2f8b0.png",
    id: "f5e7",
  },
  {
    _id: "61effe70ec10485031ae832b",
    title: "PO, 프로덕트 디자이너가 개발 아키텍처까지 알아야하나요?",
    subtitle: "나도 개발을 배워야하나.. 생각했다면 그럴 필요 없습니다.",
    authorId: "y",
    date: "2022.01.26",
    slug: "Architecture-sync",
    category: "e",
    tag: ["b", "po", "product-owner", "architecture", "product designer"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/69/69248cb9-b70b-4361-9d26-7096a8ab1bf7.jpeg",
    id: "558d",
  },
  {
    _id: "618b6eb3623c6a8bb54eaecd",
    title: "원칙에 극도로 몰입한 인턴",
    subtitle: "인턴이 느낀 힐링페이퍼의 핵심가치에 대하여",
    authorId: "kyla.jo@healingpaper.com",
    date: "2021.11.11",
    slug: "corevalues",
    category: "r",
    tag: ["d"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/97/97dd892c-2b6e-4b31-bdd4-918c2dd48553.png",
    id: "5817",
  },
  {
    _id: "614032ce5ea287a417d6836f",
    title: "첫 출근하면 경험하는 것들",
    subtitle: "매일 성장하는 Sync & Align 온보딩을 소개합니다",
    authorId: "s",
    date: "2021.09.14",
    slug: "onboarding",
    category: "l",
    tag: ["온보딩", "d", "피드백"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/65/65dfdee8-65e5-4c65-953b-942ff4952fbb.png",
    id: "eab9",
  },
  {
    _id: "6107d8556b2b4f7073527c92",
    title: "외부 툴 변경에 휘둘리지 않는 서버 코드 작성기",
    subtitle:
      "사례로 보는, DIP를 이용한 외부 툴에 의존하지 않는 도메인 모델 설계",
    authorId: "O",
    date: "2021.08.19",
    slug: "dependency-inversion-principle",
    category: "i",
    tag: [
      "DIP",
      "Dependency Inversion",
      "Dependency Inversion Principle",
      "의존성 역전 원칙",
    ],
    status: "t",
    thumbnailUrl: null,
    id: "7a06",
  },
  {
    _id: "607e4639c52f631acbc7d15b",
    title: "최소 비용으로 때깔나는 브랜드 영상광고 만들기",
    subtitle: "유명 대행사 없이 브랜드 필름을 만들어보자",
    authorId: "hassan@healingpaper.com",
    date: null,
    slug: "brandfilm-making",
    category: "r",
    tag: ["브랜드마케팅", "광고", "유튜브"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/ab/ab932c65-0f34-4d3c-af39-69cd2db1b64d.jpeg",
    id: "553b",
  },
  {
    _id: "607e4599c52f634238c7d15a",
    title: "RxJava to Coroutine, 네트워크 처리에 코루틴을 적용했더니?!",
    subtitle: null,
    authorId: "dalton.lee@healingpaper.com",
    date: null,
    slug: "android-coroutine",
    category: "n",
    tag: ["u", "RxJava", "Z", "Kotlin", "Retrofit", "OkHttp"],
    status: "t",
    thumbnailUrl: null,
    id: "4363",
  },
  {
    _id: "6062f516ea48fbf4b50bf441",
    title: "도시 이름으로 협업하는 방법",
    subtitle: "왜 팀 이름이 곡성, 평양, 월가야?",
    authorId: "s",
    date: "2021.03.30",
    slug: "city-squad",
    category: "l",
    tag: ["d", "스쿼드", "팀이름", "프로덕트오너"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/e1/e1e62768-28ab-45f0-8757-e05a95249b68.jpeg",
    id: "2220",
  },
  {
    _id: "6049bb28c9f26b8403641cfd",
    title: "이직률 0% 조직의 동료와 문화",
    subtitle: "나는 매일 새로운 회사를 다닌다",
    authorId: "o",
    date: "2021.03.11",
    slug: "zero-percent",
    category: "l",
    tag: ["d", "동료"],
    status: "t",
    thumbnailUrl: null,
    id: "5d49",
  },
  {
    _id: "604891cba36fb150205cbd7b",
    title: "당신이 좋은 의사를 만날 확률",
    subtitle: "미용의료 플랫폼이 바꾸는 4가지 지표",
    authorId: "s",
    date: "2021.03.10",
    slug: "good-doctor",
    category: "I",
    tag: ["P", "Problem", "$", "Medical Beauty"],
    status: "t",
    thumbnailUrl: null,
    id: "7f4c",
  },
  {
    _id: "602e4993a36fb10b245cbcb1",
    title: "일러스트 시스템 제작기",
    subtitle: "브랜드 결을 맞추면서 구성원에게 디자인 밀키트 제공하기",
    authorId: "tt",
    date: "2021.02.25",
    slug: "illust-system-for-gangnamunni",
    category: "e",
    tag: ["designsystem", "illustsystem", "H"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/06/06c5b2ba-f8c8-464d-8db9-9928f5a056ca.png",
    id: "6757",
  },
  {
    _id: "601cd69381b69293f9660501",
    title: "실패를 통해 배우는 AB테스트",
    subtitle: "테스트가 중요한거는 알겠는데 어떻게 해야 잘할 수 있을까?",
    authorId: "p",
    date: "2021.02.17",
    slug: "AB-test-Baisc",
    category: "e",
    tag: ["ABtest", "AB테스트", "실험", "통제변수"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/f6/f6ecea42-198c-4d0f-a4f1-c1f001c5c787.jpeg",
    id: "8a76",
  },
  {
    _id: "6029e9f8c9f26be88c641be2",
    title: "사용자들의 놀이터에서 비즈니스 임팩트 내기",
    subtitle: "헤비유저가 되어보려다 제품 개선한 썰",
    authorId: "y",
    date: "2021.02.15",
    slug: "community-business-impact",
    category: "e",
    tag: ["community", "b", "productdesign", "businessimpact"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/86/86bf2f58-6c4d-4366-92d9-43bf6c8fe5eb.jpeg",
    id: "75b2",
  },
  {
    _id: "60111661072379344c0064bf",
    title: "나의 대충 그려졌고 소중한 와이어프레임",
    subtitle: "와이어프레임으로 더 빠르게 팀과 이야기하기",
    authorId: "B",
    date: "2021.01.27",
    slug: "communication-with-wireframe",
    category: "e",
    tag: ["Wireframe", "c", "Communication", "J"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/b4/b41153ff-92e9-43cd-950a-014f0b30cb89.png",
    id: "4835",
  },
  {
    _id: "5ff9ad55572a4d47dca3c82c",
    title: "디자인 챕터의 새롭고 신나는 온라인 회고 방법",
    subtitle: "떨어져있지만 함께하는 느낌으로 회고하기",
    authorId: "p",
    date: "2021.01.09",
    slug: "Retrospective",
    category: "e",
    tag: ["디자인 ", "회고", "코로나", "비대면"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/92/926ade05-4c60-4e5d-b900-f6a4b38a9429.jpeg",
    id: "3050",
  },
  {
    _id: "5fcdbed638d014010fc39a2f",
    title: "응급실 원칙 1. 가장 위태로운 환자가 최우선",
    subtitle: "의료 스타트업에서 보내는 1년의 회고",
    authorId: "s",
    date: "2020.12.07",
    slug: "emergency",
    category: "I",
    tag: ["mission", "at", "R"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/c8/c84b938e-094d-4074-a12d-a3e79776b229.jpeg",
    id: "c668",
  },
  {
    _id: "5f602d436f0106458edd0ccc",
    title: "프로덕트 디자이너가 PO를 한다면?",
    subtitle: "우당탕탕 PO 겸임기를 통해 얻은 것",
    authorId: "y",
    date: "2020.09.15",
    slug: "product-design-and-product-owner",
    category: "e",
    tag: ["productdesigner", "productowner", "po"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/cd/cd343e94-9912-407f-8a7a-6c7c3abb857b.jpeg",
    id: "495c",
  },
  {
    _id: "5f504fea48470c711b3c001b",
    title: "MVVM Anti Pattern",
    subtitle: "MVVM Architecture을 적용할 때 피해야할 패턴에 대하여 알아보자",
    authorId: "et",
    date: "2020.09.03",
    slug: "mvvm_anti_pattern",
    category: "n",
    tag: ["u", "MVVM"],
    status: "t",
    thumbnailUrl: null,
    id: "a494",
  },
  {
    _id: "5f4de8cf522a3a4504dba326",
    title: "제프 베조스의 편지를 계속 엿보는 이유",
    subtitle: "Stand on the shoulders of giants!",
    authorId: "s",
    date: "2020.09.01",
    slug: "letters",
    category: "l",
    tag: ["R", "g", "Amazon", "인재상"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/d5/d5274bf5-67f1-418b-a29c-9a82a71fb2b5.png",
    id: "84c8",
  },
  {
    _id: "5f3f836eb95eb5c87afda67e",
    title: "우리는 왜 Workshop을 갈까요?",
    subtitle: "개발 챕터 2020 여름 Workshop 후기",
    authorId: "roy.shin@healingpaper.com",
    date: "2020.08.21",
    slug: "ch-dev-workshop-2020-summer",
    category: "l",
    tag: ["E", "g"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/thumbnail/ch-dev-workshop-2020-summer.jpg",
    id: "964a",
  },
  {
    _id: "5f3d07e495f1a2340fa5b27d",
    title: "불법 성형 광고, 그것이 알고 싶다",
    subtitle: "'성형외과가 지켜야 할 광고 가이드'를 발간하며",
    authorId: "s",
    date: "2020.08.19",
    slug: "ads-guide",
    category: "I",
    tag: ["의료광고", "광고제작가이드", "at"],
    status: "t",
    thumbnailUrl: "https://static.blog.gangnamunni.com/thumbnail/ads-guide.png",
    id: "422e",
  },
  {
    _id: "5f23d4cffb46bd0a9ee535b7",
    title: "UT(사용성 테스트)로 고객 이해하기",
    subtitle: "사용성 테스트를 통해 고객과 친밀도 쌓는 법",
    authorId: "B",
    date: "2020.07.31",
    slug: "usability-test",
    category: "e",
    tag: ["c", "q", "M", "UsabilityTest", "X"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/9348c5b4-fcc6-46be-ae0f-3435e5c2eed4.png",
    id: "69b9",
  },
  {
    _id: "5f0e9d33cc01f59cdb1dc8d9",
    title: "Annotation 안에서 무슨 일이 일어나는 거지? 2편",
    subtitle: "Kotlin 으로 Custom Annotation 만들어보기 - Code generation 편",
    authorId: "it",
    date: "2020.07.15",
    slug: "kotlin-annotation-codegeneration",
    category: "n",
    tag: [],
    status: "t",
    thumbnailUrl: null,
    id: "6b6b",
  },
  {
    _id: "5ef864d9f4793f0f67529aa2",
    title:
      "Spring 의 동기, 비동기, 배치 처리시 항상 context 를 유지하고 로깅하기",
    subtitle:
      "async 처리시 로깅을 위해 ThreadLocal, MDC, 그리고 TaskDecorator 를 활용해보자",
    authorId: "o",
    date: "2020.07.09",
    slug: "mdc-context-task-decorator",
    category: "i",
    tag: [
      "spring",
      "async",
      "logging",
      "mdc",
      "threadLocal",
      "TaskDecorator",
      "context",
      "batch",
      "thread",
    ],
    status: "t",
    thumbnailUrl: null,
    id: "c809",
  },
  {
    _id: "5ef86194f4793f7a3c529aa1",
    title:
      "Hibernate entity 에 Lombok 사용 시  stackoverflow 혹은 LazyInitializationException 이슈",
    subtitle: "Annotation 도 ORM 도 잘 알고 써야 제 맛",
    authorId: "o",
    date: "2020.07.02",
    slug: "hibernate_lombok_lazy",
    category: "i",
    tag: ["hibernate", "lombok", "annotation", "@Data", "ORM"],
    status: "t",
    thumbnailUrl: null,
    id: "c799",
  },
  {
    _id: "5ef851f6f4793fbea1529a9f",
    title: "AWS RDS 에서 MySql 한글 및 이모지 처리 (utf8, utf8mb4)",
    subtitle: "우리나라 개발자가 전세계 소프트웨어 다 만들면 참 좋겠다",
    authorId: "o",
    date: "2020.06.20",
    slug: "aws-rds-mysql-utf8mb4",
    category: "i",
    tag: ["mysql", "aws", "rds", "utf8", "utf8mb4", "emoji", "이모지"],
    status: "t",
    thumbnailUrl: null,
    id: "8554",
  },
  {
    _id: "5eeca3cbca4959c2ce3b82f2",
    title: "디자인 챕터는 왜 존재할까?",
    subtitle: " 디자인 챕터의 미션&비전 수립기",
    authorId: "design@healingpaper.com",
    date: "2020.06.19",
    slug: "mission-vision-of-designchapter",
    category: "e",
    tag: ["c", "P", "Vision"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/3cc4c7ee-c7f3-4bcb-9f5a-7bf670fdb607.jpeg",
    id: "547e",
  },
  {
    _id: "5ef858cef4793f15eb529aa0",
    title: "MySQL 그날의 끝 시간(23:59:59) 저장 시 주의 할 점",
    subtitle: "Datetime 과 Timestamp 등 시간 저장은 늘 긴장해야 한다",
    authorId: "o",
    date: "2020.06.15",
    slug: "mysql-endtime-timestamp",
    category: "i",
    tag: ["mysql", "datetime", "timestamp"],
    status: "t",
    thumbnailUrl: null,
    id: "f9b2",
  },
  {
    _id: "5ede08d36875d45c4bf68fef",
    title: "CEO 생각 쫓기",
    subtitle: "철학과 조직, 비즈니스의 상관 관계",
    authorId: "s",
    date: "2020.06.08",
    slug: "radical-philosophy",
    category: "l",
    tag: ["R", "g", "Corevalue", "Principle", "기업철학"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/526f34aa-e4b0-41b4-aa49-06985a340cf1.jpeg",
    id: "02b0",
  },
  {
    _id: "5ed7730ae6154b41c488cf2b",
    title: "UI 텍스트 가이드라인 제작기",
    subtitle: "텍스트에  뿌리기",
    authorId: "tt",
    date: "2020.06.03",
    slug: "ui-text-guideline",
    category: "e",
    tag: ["UI Text Guideline", "h"],
    status: "t",
    thumbnailUrl:
      "https://static.blog.gangnamunni.com/files/e9b58151-93d5-44cf-9419-3c21615668da.png",
    id: "622a",
  },
  {
    _id: "5ed09e2578db1f2843390729",
    title: "ViewPager2 파헤치기",
    subtitle: null,
    authorId: "et",
    date: "2020.05.29",
    slug: "viewpager2",
    category: "n",
    tag: ["ViewPager", "ViewPager2", "u"],
    status: "t",
    thumbnailUrl: null,
    id: "8f07",
  },
  {
    _id: "5ecc6c89f43a62915c9668b7",
    title: "타입스크립트로 슬랙 앱(봇) 만들기 - 기초편",
    subtitle: "슬랙 앱을 통해 간단한 메시지 전송 기능을 만들어보자.",
    authorId: "mark.choi@healingpaper.com",
    date: "2020.05.27",
    slug: "typescript-slack-bot",
    category: "m",
    tag: ["슬랙", "Slack", "Typescript", "슬랙봇", "타입스크립트", "슬랙앱"],
    status: "t",
    thumbnailUrl: null,
    id: "e355",
  },
];
