import { HANTEO_MAMBER } from "@/types";

export const HANTEO_MEMBERS: HANTEO_MAMBER[] = [
  {
    id: 1,
    name: "김재운",
    role: "프로젝트 매니저",
    department: "서비스개발실",
    stack: ["풀스택", "IOS 개발자"],
    residence: "캐나다",
    dateOfEmployment: "Fabruary 1, 2019",
    info: "캠핑에 취미를 가져볼까합니다?",
    linkedIn: "http://www.linkedin.com/in/jaewoon-kim",
    email: "htjw@hanteo.com",
    gmail: "dnswkdl501@gmail.com",
    github: "https://github.com/JaeDev",
    phone: "01045319194",
    likeFood: [],
  },
  {
    id: 2,
    name: "김준완",
    role: "사원",
    department: "서비스개발실",
    stack: ["??"],
    residence: "서울",
    dateOfEmployment: "Nov 8, 2023",
    info: "",
    linkedIn: "",
    email: "jwk7890@hanteo.com",
    gmail: "jjwwkk7890@gmail.com",
    github: "",
    phone: "01093977790",
    likeFood: [],
  },
  {
    id: 3,
    name: "류동재",
    role: "사원",
    stack: ["백엔드 개발자"],
    department: "서비스개발실",
    residence: "서울",
    dateOfEmployment: "Feb 7, 2022",
    info: "모든 건..기세다",
    linkedIn: "",
    email: "rdj1014@hanteo.com",
    gmail: "rdj10149@gmail.com",
    github: "https://github.com/ryudongjae",
    phone: "01079422492",
    likeFood: [],
  },
  {
    id: 4,
    name: "박병서",
    role: "본부장",
    department: "서비스개발실",
    stack: [
      "백엔드 개발자",
      "프론트엔드 개발자",
      "서비스 매니저",
      "안드로이드 개발자",
    ],
    residence: "서울",
    dateOfEmployment: "Apr 1, 2024",
    info: "",
    linkedIn: "",
    email: "dev.bspark@hanteo.com",
    gmail: "dev.bspark@gmail.com",
    github: "",
    phone: "01068996794",
    likeFood: [],
  },
  {
    id: 5,
    name: "신동한",
    role: "주임",
    department: "서비스개발실",
    stack: ["백엔드 개발자"],
    residence: "서울",
    dateOfEmployment: "Feb 8, 2021",
    info: "",
    linkedIn: "",
    email: "donghans@hanteo.com",
    gmail: "b.donghans@gmail.com",
    github: "https://github.com/donghans",
    phone: "01064151647",
    likeFood: [],
  },
  {
    id: 6,
    name: "윤주성",
    role: "팀장, 프로젝트 매니저",
    department: "서비스개발실",
    stack: ["풀스택"],
    residence: "서울",
    dateOfEmployment: "Feb 8, 2021",
    info: "",
    linkedIn: "",
    email: "pollalis2@hanteo.com",
    gmail: "pollalis2@gmail.com",
    github: "",
    phone: "01041378018",
    likeFood: [],
  },
  {
    id: 7,
    name: "이본훈",
    department: "서비스개발실",
    role: "사원",
    stack: ["프론트엔드 개발자"],
    residence: "서울",
    dateOfEmployment: "May 7, 2024",
    info: "",
    linkedIn: "",
    email: "opsizks4@hanteo.com",
    gmail: "opsizks4@gmail.com",
    github: "https://github.com/LeeBonHoon1",
    phone: "01021830828",
    likeFood: [],
  },
  {
    id: 8,
    name: "이영훈",
    role: "주임",
    department: "서비스개발실",
    stack: ["안드로이드 개발자", "프론트엔드 개발자"],
    residence: "서울",
    dateOfEmployment: "Oct 20, 2020",
    info: "지금 거의 거렁뱅이예요",
    linkedIn: "",
    email: "twnthbb@hanteo.com",
    gmail: "twnthbb@gmail.com",
    github: "https://github.com/twnth",
    phone: "01083515080",
    likeFood: [
      "국밥",
      "라면",
      "짬뽕",
      "마라탕",
      "마라샹궈",
      "삼겹살",
      "오징어 덮밥",
      "아아",
      "곱창",
      "부대찌개",
    ],
  },
  {
    id: 9,
    name: "정지현",
    role: "사원",
    department: "서비스개발실",
    stack: ["백엔드 개발자"],
    residence: "서울",
    dateOfEmployment: "Oct 11, 2023",
    info: "",
    linkedIn: "",
    email: "ironprayer1208@hanteo.com",
    gmail: "ironprayer1209@gmail.com",
    github: "https://github.com/jeongjihuyn",
    phone: "01035370775",
    likeFood: [],
  },
];
